#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff confluence-to-asciidoc.js;
then
  DOC=$(./confluence-to-asciidoc.js --help)
  npm run hooks:pre-commit -- "$DOC"
  git add README.md
fi;

